-- Generated: local sound files. WA/PA copied from the WeakAuras addon (GPL-2.0; sound files carry their own
-- Creative Commons licenses, see WeakAuras\Media\Provided by.txt). Files directly in Media\Audio and in Custom = Xaya's own.
-- BW = copied from the BigWigs addon (per-folder license.txt files came along; BigWigs is All Rights Reserved / several packs are CC BY-NC;
-- Heroes = Blizzard-owned Heroes of the Storm voice lines). Personal use only: never commit or share these.
-- New files need a full game restart (not /reload) before the client can play them.
local addonName, ns = ...
ns.LocalSounds = {
    { "[Local] letfly", "Interface\\AddOns\\XayaUI\\Media\\Audio\\letfly.ogg" },
    { "[WA] AcousticGuitar", "Interface\\AddOns\\XayaUI\\Media\\Audio\\WA\\AcousticGuitar.ogg" },
    { "[WA] Adds", "Interface\\AddOns\\XayaUI\\Media\\Audio\\WA\\Adds.ogg" },
    { "[WA] AirHorn", "Interface\\AddOns\\XayaUI\\Media\\Audio\\WA\\AirHorn.ogg" },
    { "[WA] Applause", "Interface\\AddOns\\XayaUI\\Media\\Audio\\WA\\Applause.ogg" },
    { "[WA] BananaPeelSlip", "Interface\\AddOns\\XayaUI\\Media\\Audio\\WA\\BananaPeelSlip.ogg" },
    { "[WA] BatmanPunch", "Interface\\AddOns\\XayaUI\\Media\\Audio\\WA\\BatmanPunch.ogg" },
    { "[WA] BikeHorn", "Interface\\AddOns\\XayaUI\\Media\\Audio\\WA\\BikeHorn.ogg" },
    { "[WA] Blast", "Interface\\AddOns\\XayaUI\\Media\\Audio\\WA\\Blast.ogg" },
    { "[WA] Bleat", "Interface\\AddOns\\XayaUI\\Media\\Audio\\WA\\Bleat.ogg" },
    { "[WA] Boss", "Interface\\AddOns\\XayaUI\\Media\\Audio\\WA\\Boss.ogg" },
    { "[WA] BoxingArenaSound", "Interface\\AddOns\\XayaUI\\Media\\Audio\\WA\\BoxingArenaSound.ogg" },
    { "[WA] Brass", "Interface\\AddOns\\XayaUI\\Media\\Audio\\WA\\Brass.mp3" },
    { "[WA] CartoonVoiceBaritone", "Interface\\AddOns\\XayaUI\\Media\\Audio\\WA\\CartoonVoiceBaritone.ogg" },
    { "[WA] CartoonWalking", "Interface\\AddOns\\XayaUI\\Media\\Audio\\WA\\CartoonWalking.ogg" },
    { "[WA] CatMeow2", "Interface\\AddOns\\XayaUI\\Media\\Audio\\WA\\CatMeow2.ogg" },
    { "[WA] ChickenAlarm", "Interface\\AddOns\\XayaUI\\Media\\Audio\\WA\\ChickenAlarm.ogg" },
    { "[WA] Circle", "Interface\\AddOns\\XayaUI\\Media\\Audio\\WA\\Circle.ogg" },
    { "[WA] CowMooing", "Interface\\AddOns\\XayaUI\\Media\\Audio\\WA\\CowMooing.ogg" },
    { "[WA] Cross", "Interface\\AddOns\\XayaUI\\Media\\Audio\\WA\\Cross.ogg" },
    { "[WA] Diamond", "Interface\\AddOns\\XayaUI\\Media\\Audio\\WA\\Diamond.ogg" },
    { "[WA] DontRelease", "Interface\\AddOns\\XayaUI\\Media\\Audio\\WA\\DontRelease.ogg" },
    { "[WA] DoubleWhoosh", "Interface\\AddOns\\XayaUI\\Media\\Audio\\WA\\DoubleWhoosh.ogg" },
    { "[WA] Drums", "Interface\\AddOns\\XayaUI\\Media\\Audio\\WA\\Drums.ogg" },
    { "[WA] Empowered", "Interface\\AddOns\\XayaUI\\Media\\Audio\\WA\\Empowered.ogg" },
    { "[WA] ErrorBeep", "Interface\\AddOns\\XayaUI\\Media\\Audio\\WA\\ErrorBeep.ogg" },
    { "[WA] Focus", "Interface\\AddOns\\XayaUI\\Media\\Audio\\WA\\Focus.ogg" },
    { "[WA] Glass", "Interface\\AddOns\\XayaUI\\Media\\Audio\\WA\\Glass.mp3" },
    { "[WA] GoatBleating", "Interface\\AddOns\\XayaUI\\Media\\Audio\\WA\\GoatBleating.ogg" },
    { "[WA] HeartbeatSingle", "Interface\\AddOns\\XayaUI\\Media\\Audio\\WA\\HeartbeatSingle.ogg" },
    { "[WA] Idiot", "Interface\\AddOns\\XayaUI\\Media\\Audio\\WA\\Idiot.ogg" },
    { "[WA] KittenMeow", "Interface\\AddOns\\XayaUI\\Media\\Audio\\WA\\KittenMeow.ogg" },
    { "[WA] Left", "Interface\\AddOns\\XayaUI\\Media\\Audio\\WA\\Left.ogg" },
    { "[WA] Moon", "Interface\\AddOns\\XayaUI\\Media\\Audio\\WA\\Moon.ogg" },
    { "[WA] Next", "Interface\\AddOns\\XayaUI\\Media\\Audio\\WA\\Next.ogg" },
    { "[WA] OhNo", "Interface\\AddOns\\XayaUI\\Media\\Audio\\WA\\OhNo.ogg" },
    { "[WA] Portal", "Interface\\AddOns\\XayaUI\\Media\\Audio\\WA\\Portal.ogg" },
    { "[WA] Protected", "Interface\\AddOns\\XayaUI\\Media\\Audio\\WA\\Protected.ogg" },
    { "[WA] Release", "Interface\\AddOns\\XayaUI\\Media\\Audio\\WA\\Release.ogg" },
    { "[WA] Right", "Interface\\AddOns\\XayaUI\\Media\\Audio\\WA\\Right.ogg" },
    { "[WA] RingingPhone", "Interface\\AddOns\\XayaUI\\Media\\Audio\\WA\\RingingPhone.ogg" },
    { "[WA] RoaringLion", "Interface\\AddOns\\XayaUI\\Media\\Audio\\WA\\RoaringLion.ogg" },
    { "[WA] RobotBlip", "Interface\\AddOns\\XayaUI\\Media\\Audio\\WA\\RobotBlip.ogg" },
    { "[WA] RoosterChickenCalls", "Interface\\AddOns\\XayaUI\\Media\\Audio\\WA\\RoosterChickenCalls.ogg" },
    { "[WA] RunAway", "Interface\\AddOns\\XayaUI\\Media\\Audio\\WA\\RunAway.ogg" },
    { "[WA] SharpPunch", "Interface\\AddOns\\XayaUI\\Media\\Audio\\WA\\SharpPunch.ogg" },
    { "[WA] SheepBleat", "Interface\\AddOns\\XayaUI\\Media\\Audio\\WA\\SheepBleat.ogg" },
    { "[WA] Shotgun", "Interface\\AddOns\\XayaUI\\Media\\Audio\\WA\\Shotgun.ogg" },
    { "[WA] Skull", "Interface\\AddOns\\XayaUI\\Media\\Audio\\WA\\Skull.ogg" },
    { "[WA] Spread", "Interface\\AddOns\\XayaUI\\Media\\Audio\\WA\\Spread.ogg" },
    { "[WA] Square", "Interface\\AddOns\\XayaUI\\Media\\Audio\\WA\\Square.ogg" },
    { "[WA] SqueakyToyShort", "Interface\\AddOns\\XayaUI\\Media\\Audio\\WA\\SqueakyToyShort.ogg" },
    { "[WA] SquishFart", "Interface\\AddOns\\XayaUI\\Media\\Audio\\WA\\SquishFart.ogg" },
    { "[WA] Stack", "Interface\\AddOns\\XayaUI\\Media\\Audio\\WA\\Stack.ogg" },
    { "[WA] Star", "Interface\\AddOns\\XayaUI\\Media\\Audio\\WA\\Star.ogg" },
    { "[WA] Switch", "Interface\\AddOns\\XayaUI\\Media\\Audio\\WA\\Switch.ogg" },
    { "[WA] SynthChord", "Interface\\AddOns\\XayaUI\\Media\\Audio\\WA\\SynthChord.ogg" },
    { "[WA] TadaFanfare", "Interface\\AddOns\\XayaUI\\Media\\Audio\\WA\\TadaFanfare.ogg" },
    { "[WA] Taunt", "Interface\\AddOns\\XayaUI\\Media\\Audio\\WA\\Taunt.ogg" },
    { "[WA] TempleBellHuge", "Interface\\AddOns\\XayaUI\\Media\\Audio\\WA\\TempleBellHuge.ogg" },
    { "[WA] Torch", "Interface\\AddOns\\XayaUI\\Media\\Audio\\WA\\Torch.ogg" },
    { "[WA] Triangle", "Interface\\AddOns\\XayaUI\\Media\\Audio\\WA\\Triangle.ogg" },
    { "[WA] WarningSiren", "Interface\\AddOns\\XayaUI\\Media\\Audio\\WA\\WarningSiren.ogg" },
    { "[WA] WaterDrop", "Interface\\AddOns\\XayaUI\\Media\\Audio\\WA\\WaterDrop.ogg" },
    { "[WA] Xylophone", "Interface\\AddOns\\XayaUI\\Media\\Audio\\WA\\Xylophone.ogg" },
    { "[PA] aggro", "Interface\\AddOns\\XayaUI\\Media\\Audio\\PA\\aggro.ogg" },
    { "[PA] Arrow_Swoosh", "Interface\\AddOns\\XayaUI\\Media\\Audio\\PA\\Arrow_Swoosh.ogg" },
    { "[PA] bam", "Interface\\AddOns\\XayaUI\\Media\\Audio\\PA\\bam.ogg" },
    { "[PA] bear_polar", "Interface\\AddOns\\XayaUI\\Media\\Audio\\PA\\bear_polar.ogg" },
    { "[PA] bigkiss", "Interface\\AddOns\\XayaUI\\Media\\Audio\\PA\\bigkiss.ogg" },
    { "[PA] BITE", "Interface\\AddOns\\XayaUI\\Media\\Audio\\PA\\BITE.ogg" },
    { "[PA] burp4", "Interface\\AddOns\\XayaUI\\Media\\Audio\\PA\\burp4.ogg" },
    { "[PA] cat2", "Interface\\AddOns\\XayaUI\\Media\\Audio\\PA\\cat2.ogg" },
    { "[PA] chant2", "Interface\\AddOns\\XayaUI\\Media\\Audio\\PA\\chant2.ogg" },
    { "[PA] chant4", "Interface\\AddOns\\XayaUI\\Media\\Audio\\PA\\chant4.ogg" },
    { "[PA] chimes", "Interface\\AddOns\\XayaUI\\Media\\Audio\\PA\\chimes.ogg" },
    { "[PA] cookie", "Interface\\AddOns\\XayaUI\\Media\\Audio\\PA\\cookie.ogg" },
    { "[PA] ESPARK1", "Interface\\AddOns\\XayaUI\\Media\\Audio\\PA\\ESPARK1.ogg" },
    { "[PA] Fireball", "Interface\\AddOns\\XayaUI\\Media\\Audio\\PA\\Fireball.ogg" },
    { "[PA] Gasp", "Interface\\AddOns\\XayaUI\\Media\\Audio\\PA\\Gasp.ogg" },
    { "[PA] heartbeat", "Interface\\AddOns\\XayaUI\\Media\\Audio\\PA\\heartbeat.ogg" },
    { "[PA] hic3", "Interface\\AddOns\\XayaUI\\Media\\Audio\\PA\\hic3.ogg" },
    { "[PA] huh_1", "Interface\\AddOns\\XayaUI\\Media\\Audio\\PA\\huh_1.ogg" },
    { "[PA] hurricane", "Interface\\AddOns\\XayaUI\\Media\\Audio\\PA\\hurricane.ogg" },
    { "[PA] hyena", "Interface\\AddOns\\XayaUI\\Media\\Audio\\PA\\hyena.ogg" },
    { "[PA] kaching", "Interface\\AddOns\\XayaUI\\Media\\Audio\\PA\\kaching.ogg" },
    { "[PA] moan", "Interface\\AddOns\\XayaUI\\Media\\Audio\\PA\\moan.ogg" },
    { "[PA] panther1", "Interface\\AddOns\\XayaUI\\Media\\Audio\\PA\\panther1.ogg" },
    { "[PA] phone", "Interface\\AddOns\\XayaUI\\Media\\Audio\\PA\\phone.ogg" },
    { "[PA] PUNCH", "Interface\\AddOns\\XayaUI\\Media\\Audio\\PA\\PUNCH.ogg" },
    { "[PA] rainroof", "Interface\\AddOns\\XayaUI\\Media\\Audio\\PA\\rainroof.ogg" },
    { "[PA] rocket", "Interface\\AddOns\\XayaUI\\Media\\Audio\\PA\\rocket.ogg" },
    { "[PA] shipswhistle", "Interface\\AddOns\\XayaUI\\Media\\Audio\\PA\\shipswhistle.ogg" },
    { "[PA] shot", "Interface\\AddOns\\XayaUI\\Media\\Audio\\PA\\shot.ogg" },
    { "[PA] snakeatt", "Interface\\AddOns\\XayaUI\\Media\\Audio\\PA\\snakeatt.ogg" },
    { "[PA] sneeze", "Interface\\AddOns\\XayaUI\\Media\\Audio\\PA\\sneeze.ogg" },
    { "[PA] sonar", "Interface\\AddOns\\XayaUI\\Media\\Audio\\PA\\sonar.ogg" },
    { "[PA] splash", "Interface\\AddOns\\XayaUI\\Media\\Audio\\PA\\splash.ogg" },
    { "[PA] Squeakypig", "Interface\\AddOns\\XayaUI\\Media\\Audio\\PA\\Squeakypig.ogg" },
    { "[PA] swordecho", "Interface\\AddOns\\XayaUI\\Media\\Audio\\PA\\swordecho.ogg" },
    { "[PA] throwknife", "Interface\\AddOns\\XayaUI\\Media\\Audio\\PA\\throwknife.ogg" },
    { "[PA] thunder", "Interface\\AddOns\\XayaUI\\Media\\Audio\\PA\\thunder.ogg" },
    { "[PA] wickedmalelaugh1", "Interface\\AddOns\\XayaUI\\Media\\Audio\\PA\\wickedmalelaugh1.ogg" },
    { "[PA] wilhelm", "Interface\\AddOns\\XayaUI\\Media\\Audio\\PA\\wilhelm.ogg" },
    { "[PA] wlaugh", "Interface\\AddOns\\XayaUI\\Media\\Audio\\PA\\wlaugh.ogg" },
    { "[PA] wolf5", "Interface\\AddOns\\XayaUI\\Media\\Audio\\PA\\wolf5.ogg" },
    { "[PA] yeehaw", "Interface\\AddOns\\XayaUI\\Media\\Audio\\PA\\yeehaw.ogg" },
    { "[BW] Alarm", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Alarm.ogg" },
    { "[BW] Alert", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Alert.ogg" },
    { "[BW] Info", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Info.ogg" },
    { "[BW] Long", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Long.ogg" },
    { "[BW] spell_on_you", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\spell_on_you.ogg" },
    { "[BW] spell_under_you", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\spell_under_you.ogg" },
    { "[BW] Victory", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Victory.ogg" },
    { "[BW] VictoryClassic", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\VictoryClassic.ogg" },
    { "[BW] VictoryLong", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\VictoryLong.ogg" },
    { "[BW Amy] 1", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Amy\\1.ogg" },
    { "[BW Amy] 2", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Amy\\2.ogg" },
    { "[BW Amy] 3", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Amy\\3.ogg" },
    { "[BW Amy] 4", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Amy\\4.ogg" },
    { "[BW Amy] 5", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Amy\\5.ogg" },
    { "[BW Amy] 6", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Amy\\6.ogg" },
    { "[BW Amy] 7", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Amy\\7.ogg" },
    { "[BW Amy] 8", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Amy\\8.ogg" },
    { "[BW Amy] 9", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Amy\\9.ogg" },
    { "[BW Amy] 10", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Amy\\10.ogg" },
    { "[BW Countdown Amy] Amy_Countdown1", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\AuraCountdowns\\Amy\\Amy_Countdown1.ogg" },
    { "[BW Countdown Amy] Amy_Countdown2", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\AuraCountdowns\\Amy\\Amy_Countdown2.ogg" },
    { "[BW Countdown Amy] Amy_Countdown3", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\AuraCountdowns\\Amy\\Amy_Countdown3.ogg" },
    { "[BW Countdown Amy] Amy_Countdown4", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\AuraCountdowns\\Amy\\Amy_Countdown4.ogg" },
    { "[BW Countdown Amy] Amy_Countdown5", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\AuraCountdowns\\Amy\\Amy_Countdown5.ogg" },
    { "[BW Countdown Amy] Amy_Countdown6", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\AuraCountdowns\\Amy\\Amy_Countdown6.ogg" },
    { "[BW Countdown Amy] Amy_Countdown7", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\AuraCountdowns\\Amy\\Amy_Countdown7.ogg" },
    { "[BW Countdown Amy] Amy_Countdown8", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\AuraCountdowns\\Amy\\Amy_Countdown8.ogg" },
    { "[BW Countdown Amy] Amy_Countdown9", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\AuraCountdowns\\Amy\\Amy_Countdown9.ogg" },
    { "[BW Countdown Amy] Amy_Countdown10", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\AuraCountdowns\\Amy\\Amy_Countdown10.ogg" },
    { "[BW Countdown Amy] Amy_Countdown11", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\AuraCountdowns\\Amy\\Amy_Countdown11.ogg" },
    { "[BW Countdown Amy] Amy_Countdown12", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\AuraCountdowns\\Amy\\Amy_Countdown12.ogg" },
    { "[BW Countdown Amy] Amy_Countdown13", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\AuraCountdowns\\Amy\\Amy_Countdown13.ogg" },
    { "[BW Countdown Amy] Amy_Countdown14", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\AuraCountdowns\\Amy\\Amy_Countdown14.ogg" },
    { "[BW Countdown Amy] Amy_Countdown15", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\AuraCountdowns\\Amy\\Amy_Countdown15.ogg" },
    { "[BW Countdown Amy] Amy_Countdown16", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\AuraCountdowns\\Amy\\Amy_Countdown16.ogg" },
    { "[BW Countdown Amy] Amy_Countdown17", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\AuraCountdowns\\Amy\\Amy_Countdown17.ogg" },
    { "[BW Countdown Amy] Amy_Countdown18", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\AuraCountdowns\\Amy\\Amy_Countdown18.ogg" },
    { "[BW Countdown Amy] Amy_Countdown19", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\AuraCountdowns\\Amy\\Amy_Countdown19.ogg" },
    { "[BW Countdown Amy] Amy_Countdown20", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\AuraCountdowns\\Amy\\Amy_Countdown20.ogg" },
    { "[BW Countdown Amy] Amy_Countdown21", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\AuraCountdowns\\Amy\\Amy_Countdown21.ogg" },
    { "[BW Countdown Amy] Amy_Countdown22", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\AuraCountdowns\\Amy\\Amy_Countdown22.ogg" },
    { "[BW Countdown Amy] Amy_Countdown23", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\AuraCountdowns\\Amy\\Amy_Countdown23.ogg" },
    { "[BW Countdown Amy] Amy_Countdown24", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\AuraCountdowns\\Amy\\Amy_Countdown24.ogg" },
    { "[BW Countdown Amy] Amy_Countdown25", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\AuraCountdowns\\Amy\\Amy_Countdown25.ogg" },
    { "[BW Countdown Amy] Amy_Countdown26", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\AuraCountdowns\\Amy\\Amy_Countdown26.ogg" },
    { "[BW Countdown Amy] Amy_Countdown27", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\AuraCountdowns\\Amy\\Amy_Countdown27.ogg" },
    { "[BW Countdown Amy] Amy_Countdown28", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\AuraCountdowns\\Amy\\Amy_Countdown28.ogg" },
    { "[BW Countdown Amy] Amy_Countdown29", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\AuraCountdowns\\Amy\\Amy_Countdown29.ogg" },
    { "[BW Countdown Amy] Amy_Countdown30", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\AuraCountdowns\\Amy\\Amy_Countdown30.ogg" },
    { "[BW David] 1", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\David\\1.ogg" },
    { "[BW David] 2", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\David\\2.ogg" },
    { "[BW David] 3", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\David\\3.ogg" },
    { "[BW David] 4", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\David\\4.ogg" },
    { "[BW David] 5", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\David\\5.ogg" },
    { "[BW David] 6", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\David\\6.ogg" },
    { "[BW David] 7", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\David\\7.ogg" },
    { "[BW David] 8", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\David\\8.ogg" },
    { "[BW David] 9", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\David\\9.ogg" },
    { "[BW David] 10", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\David\\10.ogg" },
    { "[BW Heroes deDE female] 1", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\deDE\\female\\1.ogg" },
    { "[BW Heroes deDE female] 2", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\deDE\\female\\2.ogg" },
    { "[BW Heroes deDE female] 3", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\deDE\\female\\3.ogg" },
    { "[BW Heroes deDE female] 4", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\deDE\\female\\4.ogg" },
    { "[BW Heroes deDE female] 5", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\deDE\\female\\5.ogg" },
    { "[BW Heroes deDE male] 1", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\deDE\\male\\1.ogg" },
    { "[BW Heroes deDE male] 2", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\deDE\\male\\2.ogg" },
    { "[BW Heroes deDE male] 3", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\deDE\\male\\3.ogg" },
    { "[BW Heroes deDE male] 4", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\deDE\\male\\4.ogg" },
    { "[BW Heroes deDE male] 5", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\deDE\\male\\5.ogg" },
    { "[BW Heroes enUS female] 1", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\enUS\\female\\1.ogg" },
    { "[BW Heroes enUS female] 2", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\enUS\\female\\2.ogg" },
    { "[BW Heroes enUS female] 3", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\enUS\\female\\3.ogg" },
    { "[BW Heroes enUS female] 4", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\enUS\\female\\4.ogg" },
    { "[BW Heroes enUS female] 5", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\enUS\\female\\5.ogg" },
    { "[BW Heroes enUS male] 1", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\enUS\\male\\1.ogg" },
    { "[BW Heroes enUS male] 2", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\enUS\\male\\2.ogg" },
    { "[BW Heroes enUS male] 3", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\enUS\\male\\3.ogg" },
    { "[BW Heroes enUS male] 4", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\enUS\\male\\4.ogg" },
    { "[BW Heroes enUS male] 5", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\enUS\\male\\5.ogg" },
    { "[BW Heroes esES female] 1", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\esES\\female\\1.ogg" },
    { "[BW Heroes esES female] 2", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\esES\\female\\2.ogg" },
    { "[BW Heroes esES female] 3", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\esES\\female\\3.ogg" },
    { "[BW Heroes esES female] 4", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\esES\\female\\4.ogg" },
    { "[BW Heroes esES female] 5", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\esES\\female\\5.ogg" },
    { "[BW Heroes esES male] 1", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\esES\\male\\1.ogg" },
    { "[BW Heroes esES male] 2", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\esES\\male\\2.ogg" },
    { "[BW Heroes esES male] 3", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\esES\\male\\3.ogg" },
    { "[BW Heroes esES male] 4", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\esES\\male\\4.ogg" },
    { "[BW Heroes esES male] 5", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\esES\\male\\5.ogg" },
    { "[BW Heroes esMX male] 1", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\esMX\\male\\1.ogg" },
    { "[BW Heroes esMX male] 2", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\esMX\\male\\2.ogg" },
    { "[BW Heroes esMX male] 3", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\esMX\\male\\3.ogg" },
    { "[BW Heroes esMX male] 4", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\esMX\\male\\4.ogg" },
    { "[BW Heroes esMX male] 5", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\esMX\\male\\5.ogg" },
    { "[BW Heroes frFR female] 1", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\frFR\\female\\1.ogg" },
    { "[BW Heroes frFR female] 2", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\frFR\\female\\2.ogg" },
    { "[BW Heroes frFR female] 3", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\frFR\\female\\3.ogg" },
    { "[BW Heroes frFR female] 4", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\frFR\\female\\4.ogg" },
    { "[BW Heroes frFR female] 5", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\frFR\\female\\5.ogg" },
    { "[BW Heroes frFR male] 1", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\frFR\\male\\1.ogg" },
    { "[BW Heroes frFR male] 2", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\frFR\\male\\2.ogg" },
    { "[BW Heroes frFR male] 3", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\frFR\\male\\3.ogg" },
    { "[BW Heroes frFR male] 4", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\frFR\\male\\4.ogg" },
    { "[BW Heroes frFR male] 5", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\frFR\\male\\5.ogg" },
    { "[BW Heroes itIT female] 1", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\itIT\\female\\1.ogg" },
    { "[BW Heroes itIT female] 2", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\itIT\\female\\2.ogg" },
    { "[BW Heroes itIT female] 3", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\itIT\\female\\3.ogg" },
    { "[BW Heroes itIT female] 4", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\itIT\\female\\4.ogg" },
    { "[BW Heroes itIT female] 5", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\itIT\\female\\5.ogg" },
    { "[BW Heroes itIT male] 1", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\itIT\\male\\1.ogg" },
    { "[BW Heroes itIT male] 2", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\itIT\\male\\2.ogg" },
    { "[BW Heroes itIT male] 3", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\itIT\\male\\3.ogg" },
    { "[BW Heroes itIT male] 4", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\itIT\\male\\4.ogg" },
    { "[BW Heroes itIT male] 5", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\itIT\\male\\5.ogg" },
    { "[BW Heroes koKR female] 1", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\koKR\\female\\1.ogg" },
    { "[BW Heroes koKR female] 2", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\koKR\\female\\2.ogg" },
    { "[BW Heroes koKR female] 3", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\koKR\\female\\3.ogg" },
    { "[BW Heroes koKR female] 4", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\koKR\\female\\4.ogg" },
    { "[BW Heroes koKR female] 5", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\koKR\\female\\5.ogg" },
    { "[BW Heroes koKR male] 1", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\koKR\\male\\1.ogg" },
    { "[BW Heroes koKR male] 2", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\koKR\\male\\2.ogg" },
    { "[BW Heroes koKR male] 3", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\koKR\\male\\3.ogg" },
    { "[BW Heroes koKR male] 4", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\koKR\\male\\4.ogg" },
    { "[BW Heroes koKR male] 5", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\koKR\\male\\5.ogg" },
    { "[BW Heroes ptBR female] 1", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\ptBR\\female\\1.ogg" },
    { "[BW Heroes ptBR female] 2", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\ptBR\\female\\2.ogg" },
    { "[BW Heroes ptBR female] 3", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\ptBR\\female\\3.ogg" },
    { "[BW Heroes ptBR female] 4", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\ptBR\\female\\4.ogg" },
    { "[BW Heroes ptBR female] 5", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\ptBR\\female\\5.ogg" },
    { "[BW Heroes ptBR male] 1", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\ptBR\\male\\1.ogg" },
    { "[BW Heroes ptBR male] 2", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\ptBR\\male\\2.ogg" },
    { "[BW Heroes ptBR male] 3", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\ptBR\\male\\3.ogg" },
    { "[BW Heroes ptBR male] 4", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\ptBR\\male\\4.ogg" },
    { "[BW Heroes ptBR male] 5", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\ptBR\\male\\5.ogg" },
    { "[BW Heroes ruRU female] 1", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\ruRU\\female\\1.ogg" },
    { "[BW Heroes ruRU female] 2", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\ruRU\\female\\2.ogg" },
    { "[BW Heroes ruRU female] 3", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\ruRU\\female\\3.ogg" },
    { "[BW Heroes ruRU female] 4", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\ruRU\\female\\4.ogg" },
    { "[BW Heroes ruRU female] 5", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\ruRU\\female\\5.ogg" },
    { "[BW Heroes ruRU male] 1", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\ruRU\\male\\1.ogg" },
    { "[BW Heroes ruRU male] 2", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\ruRU\\male\\2.ogg" },
    { "[BW Heroes ruRU male] 3", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\ruRU\\male\\3.ogg" },
    { "[BW Heroes ruRU male] 4", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\ruRU\\male\\4.ogg" },
    { "[BW Heroes ruRU male] 5", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\ruRU\\male\\5.ogg" },
    { "[BW Heroes zhCN female] 1", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\zhCN\\female\\1.ogg" },
    { "[BW Heroes zhCN female] 2", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\zhCN\\female\\2.ogg" },
    { "[BW Heroes zhCN female] 3", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\zhCN\\female\\3.ogg" },
    { "[BW Heroes zhCN female] 4", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\zhCN\\female\\4.ogg" },
    { "[BW Heroes zhCN female] 5", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\zhCN\\female\\5.ogg" },
    { "[BW Heroes zhCN male] 1", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\zhCN\\male\\1.ogg" },
    { "[BW Heroes zhCN male] 2", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\zhCN\\male\\2.ogg" },
    { "[BW Heroes zhCN male] 3", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\zhCN\\male\\3.ogg" },
    { "[BW Heroes zhCN male] 4", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\zhCN\\male\\4.ogg" },
    { "[BW Heroes zhCN male] 5", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\zhCN\\male\\5.ogg" },
    { "[BW Heroes zhTW female] 1", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\zhTW\\female\\1.ogg" },
    { "[BW Heroes zhTW female] 2", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\zhTW\\female\\2.ogg" },
    { "[BW Heroes zhTW female] 3", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\zhTW\\female\\3.ogg" },
    { "[BW Heroes zhTW female] 4", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\zhTW\\female\\4.ogg" },
    { "[BW Heroes zhTW female] 5", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\zhTW\\female\\5.ogg" },
    { "[BW Heroes zhTW male] 1", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\zhTW\\male\\1.ogg" },
    { "[BW Heroes zhTW male] 2", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\zhTW\\male\\2.ogg" },
    { "[BW Heroes zhTW male] 3", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\zhTW\\male\\3.ogg" },
    { "[BW Heroes zhTW male] 4", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\zhTW\\male\\4.ogg" },
    { "[BW Heroes zhTW male] 5", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Heroes\\zhTW\\male\\5.ogg" },
    { "[BW Jim] 1", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Jim\\1.ogg" },
    { "[BW Jim] 2", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Jim\\2.ogg" },
    { "[BW Jim] 3", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Jim\\3.ogg" },
    { "[BW Jim] 4", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Jim\\4.ogg" },
    { "[BW Jim] 5", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Jim\\5.ogg" },
    { "[BW Jim] 6", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Jim\\6.ogg" },
    { "[BW Jim] 7", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Jim\\7.ogg" },
    { "[BW Jim] 8", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Jim\\8.ogg" },
    { "[BW Jim] 9", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Jim\\9.ogg" },
    { "[BW Jim] 10", "Interface\\AddOns\\XayaUI\\Media\\Audio\\BW\\Jim\\10.ogg" },
}
