-- Generated: local graphics converted from Xaya's Iconography folder (PNG -> uncompressed 32-bit TGA, sizes already powers of two).
-- These are extracted Blizzard UI art: personal use only, kept out of git (see .gitignore / THIRD_PARTY.md).
-- New files need a full game restart (not /reload) before the client can draw them. Fields: label, path, width, height.
local addonName, ns = ...
ns.LocalGraphics = {
    { "[Graphics] Priest-ShadowUI", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Priest-ShadowUI.tga", 256, 128 },
    { "[Graphics] PriestInsanityBar", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\PriestInsanityBar.tga", 256, 256 },
    { "[Graphics] UI-PlayerFrame-Deathknight-Death-On", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\UI-PlayerFrame-Deathknight-Death-On.tga", 32, 32 },
    { "[Graphics] UI-PlayerFrame-Deathknight-RunicPower", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\UI-PlayerFrame-Deathknight-RunicPower.tga", 64, 64 },
    { "[Bar Fills] Arcane_Circular_Flash", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\Arcane_Circular_Flash.tga", 128, 128 },
    { "[Bar Fills] Arcane_Circular_Frame", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\Arcane_Circular_Frame.tga", 128, 128 },
    { "[Bar Fills] ArdenwealdAnima_Horizontal_Spark", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\ArdenwealdAnima_Horizontal_Spark.tga", 16, 64 },
    { "[Bar Fills] Arsenal_Horizontal_Spark", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\Arsenal_Horizontal_Spark.tga", 8, 64 },
    { "[Bar Fills] Atramedes_Circular_Flash", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\Atramedes_Circular_Flash.tga", 128, 128 },
    { "[Bar Fills] Azerite_Horizontal_Spark", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\Azerite_Horizontal_Spark.tga", 16, 64 },
    { "[Bar Fills] BastionAnima_Horizontal_Spark", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\BastionAnima_Horizontal_Spark.tga", 16, 64 },
    { "[Bar Fills] BrewingStorm_Horizontal_Fill", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\BrewingStorm_Horizontal_Fill.tga", 256, 64 },
    { "[Bar Fills] BrewingStorm_Horizontal_Spark", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\BrewingStorm_Horizontal_Spark.tga", 8, 64 },
    { "[Bar Fills] Chogall_Horizontal_Bgnd", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\Chogall_Horizontal_Bgnd.tga", 256, 64 },
    { "[Bar Fills] Chogall_Horizontal_Fill", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\Chogall_Horizontal_Fill.tga", 256, 64 },
    { "[Bar Fills] Chogall_Horizontal_Flash", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\Chogall_Horizontal_Flash.tga", 256, 64 },
    { "[Bar Fills] Chogall_Horizontal_Frame", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\Chogall_Horizontal_Frame.tga", 256, 64 },
    { "[Bar Fills] CHOGALL_HORIZONTAL_SPARK", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\CHOGALL_HORIZONTAL_SPARK.tga", 16, 64 },
    { "[Bar Fills] ConduitBolt_Horizontal_Fill", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\ConduitBolt_Horizontal_Fill.tga", 256, 64 },
    { "[Bar Fills] ConduitDiffusion_Horizontal_Fill", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\ConduitDiffusion_Horizontal_Fill.tga", 256, 64 },
    { "[Bar Fills] ConduitOvercharge_Horizontal_Fill", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\ConduitOvercharge_Horizontal_Fill.tga", 256, 64 },
    { "[Bar Fills] ConduitStatic_Horizontal_Fill", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\ConduitStatic_Horizontal_Fill.tga", 256, 64 },
    { "[Bar Fills] Darkmoon_Horizontal_Spark", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\Darkmoon_Horizontal_Spark.tga", 16, 64 },
    { "[Bar Fills] DeathwingBlood_Horizontal_Fill", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\DeathwingBlood_Horizontal_Fill.tga", 256, 64 },
    { "[Bar Fills] DeathwingBlood_Horizontal_Spark", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\DeathwingBlood_Horizontal_Spark.tga", 16, 64 },
    { "[Bar Fills] DeathwingTentacle_Horizontal_Bgnd", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\DeathwingTentacle_Horizontal_Bgnd.tga", 256, 64 },
    { "[Bar Fills] DeathwingTentacle_Horizontal_Fill", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\DeathwingTentacle_Horizontal_Fill.tga", 256, 64 },
    { "[Bar Fills] DemonHunterBarHorizontal", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\DemonHunterBarHorizontal.tga", 128, 32 },
    { "[Bar Fills] eyeofthejailer-fill", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\eyeofthejailer-fill.tga", 128, 128 },
    { "[Bar Fills] FelBreakerCaptainShield_Horizontal_Bgnd", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\FelBreakerCaptainShield_Horizontal_Bgnd.tga", 256, 64 },
    { "[Bar Fills] FelBreakerCaptainShield_Horizontal_Fill", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\FelBreakerCaptainShield_Horizontal_Fill.tga", 256, 64 },
    { "[Bar Fills] FelBreakerCaptainShield_Horizontal_Flash", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\FelBreakerCaptainShield_Horizontal_Flash.tga", 256, 64 },
    { "[Bar Fills] FelBreakerCaptainShield_Horizontal_Spark", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\FelBreakerCaptainShield_Horizontal_Spark.tga", 16, 64 },
    { "[Bar Fills] FelCorruption_Horizontal_Fill", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\FelCorruption_Horizontal_Fill.tga", 256, 64 },
    { "[Bar Fills] FelCorruption_Horizontal_Flash", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\FelCorruption_Horizontal_Flash.tga", 256, 64 },
    { "[Bar Fills] FelCorruptionDividers_Horizontal_Fill", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\FelCorruptionDividers_Horizontal_Fill.tga", 256, 64 },
    { "[Bar Fills] Fire_Circular_Frame", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\Fire_Circular_Frame.tga", 128, 128 },
    { "[Bar Fills] Fire_Horizontal_Frame", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\Fire_Horizontal_Frame.tga", 256, 64 },
    { "[Bar Fills] Fire_Vertical_Frame", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\Fire_Vertical_Frame.tga", 64, 128 },
    { "[Bar Fills] FuelGauge_Horizontal_Bgnd", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\FuelGauge_Horizontal_Bgnd.tga", 256, 64 },
    { "[Bar Fills] FuelGauge_Horizontal_Fill", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\FuelGauge_Horizontal_Fill.tga", 256, 64 },
    { "[Bar Fills] FuelGauge_Horizontal_Flash", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\FuelGauge_Horizontal_Flash.tga", 256, 64 },
    { "[Bar Fills] FuelGaugeOrange_Horizontal_Fill", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\FuelGaugeOrange_Horizontal_Fill.tga", 256, 64 },
    { "[Bar Fills] GarroshEnergy_Horizontal_Spark", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\GarroshEnergy_Horizontal_Spark.tga", 8, 64 },
    { "[Bar Fills] Generic1Player_Circular_Frame", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\Generic1Player_Circular_Frame.tga", 128, 128 },
    { "[Bar Fills] Generic1Player_Horizontal_Bgnd", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\Generic1Player_Horizontal_Bgnd.tga", 256, 64 },
    { "[Bar Fills] Generic1Player_Horizontal_Fill", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\Generic1Player_Horizontal_Fill.tga", 256, 64 },
    { "[Bar Fills] Generic1Player_Horizontal_Flash", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\Generic1Player_Horizontal_Flash.tga", 256, 64 },
    { "[Bar Fills] Generic1Player_Vertical_Bgnd", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\Generic1Player_Vertical_Bgnd.tga", 64, 128 },
    { "[Bar Fills] Generic1Player_Vertical_Fill", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\Generic1Player_Vertical_Fill.tga", 64, 128 },
    { "[Bar Fills] Generic1Player_Vertical_Flash", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\Generic1Player_Vertical_Flash.tga", 64, 128 },
    { "[Bar Fills] Generic2_Horizontal_Fill", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\Generic2_Horizontal_Fill.tga", 256, 64 },
    { "[Bar Fills] Generic2_Vertical_Fill", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\Generic2_Vertical_Fill.tga", 64, 128 },
    { "[Bar Fills] Generic3_Horizontal_Fill", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\Generic3_Horizontal_Fill.tga", 256, 64 },
    { "[Bar Fills] Generic3_Vertical_Fill", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\Generic3_Vertical_Fill.tga", 64, 128 },
    { "[Bar Fills] Ice_Circular_Frame", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\Ice_Circular_Frame.tga", 128, 128 },
    { "[Bar Fills] InquisitionTorment_Horizontal_Bgnd", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\InquisitionTorment_Horizontal_Bgnd.tga", 256, 64 },
    { "[Bar Fills] InquisitionTorment_Horizontal_Fill", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\InquisitionTorment_Horizontal_Fill.tga", 256, 64 },
    { "[Bar Fills] InquisitionTorment_Horizontal_Spark", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\InquisitionTorment_Horizontal_Spark.tga", 8, 64 },
    { "[Bar Fills] Jaina_Horizontal_Spark", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\Jaina_Horizontal_Spark.tga", 8, 64 },
    { "[Bar Fills] KargathRoarCrowd_Horizontal_Spark", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\KargathRoarCrowd_Horizontal_Spark.tga", 8, 64 },
    { "[Bar Fills] LadyAshvane_Horizontal_Spark", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\LadyAshvane_Horizontal_Spark.tga", 16, 64 },
    { "[Bar Fills] Lightning_Horizontal_Fill", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\Lightning_Horizontal_Fill.tga", 256, 64 },
    { "[Bar Fills] LightningCharges_Horizontal_Fill", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\LightningCharges_Horizontal_Fill.tga", 256, 64 },
    { "[Bar Fills] LightningCharges_Horizontal_Flash", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\LightningCharges_Horizontal_Flash.tga", 256, 64 },
    { "[Bar Fills] LightningCharges_Horizontal_Spark", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\LightningCharges_Horizontal_Spark.tga", 8, 64 },
    { "[Bar Fills] MaldraxxusAnima_Horizontal_Spark", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\MaldraxxusAnima_Horizontal_Spark.tga", 16, 64 },
    { "[Bar Fills] Meditation_Horizontal_Frame", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\Meditation_Horizontal_Frame.tga", 256, 64 },
    { "[Bar Fills] Meditation_Horizontal_Spark", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\Meditation_Horizontal_Spark.tga", 16, 64 },
    { "[Bar Fills] MetalEternium_Circular_Frame", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\MetalEternium_Circular_Frame.tga", 128, 128 },
    { "[Bar Fills] MetalPlain_Circular_Frame", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\MetalPlain_Circular_Frame.tga", 128, 128 },
    { "[Bar Fills] MoltenFeathers_Horizontal_Bgnd", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\MoltenFeathers_Horizontal_Bgnd.tga", 256, 64 },
    { "[Bar Fills] MoltenFeathers_Horizontal_Fill", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\MoltenFeathers_Horizontal_Fill.tga", 256, 64 },
    { "[Bar Fills] MoltenFeathers_Horizontal_Flash", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\MoltenFeathers_Horizontal_Flash.tga", 256, 64 },
    { "[Bar Fills] Murozond_Horizontal_Bgnd", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\Murozond_Horizontal_Bgnd.tga", 256, 64 },
    { "[Bar Fills] Murozond_Horizontal_Fill", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\Murozond_Horizontal_Fill.tga", 256, 64 },
    { "[Bar Fills] NaaruCharge_Horizontal_Fill", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\NaaruCharge_Horizontal_Fill.tga", 256, 64 },
    { "[Bar Fills] NaaruCharge_Horizontal_Flash", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\NaaruCharge_Horizontal_Flash.tga", 256, 64 },
    { "[Bar Fills] NaaruCharge_Horizontal_Spark", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\NaaruCharge_Horizontal_Spark.tga", 16, 64 },
    { "[Bar Fills] NZoth_Horizontal_Bgnd", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\NZoth_Horizontal_Bgnd.tga", 256, 64 },
    { "[Bar Fills] NZoth_Horizontal_Fill", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\NZoth_Horizontal_Fill.tga", 256, 64 },
    { "[Bar Fills] NZoth_Horizontal_Spark", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\NZoth_Horizontal_Spark.tga", 16, 64 },
    { "[Bar Fills] Onyxia_Horizontal_Fill", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\Onyxia_Horizontal_Fill.tga", 256, 64 },
    { "[Bar Fills] Onyxia_Horizontal_Flash", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\Onyxia_Horizontal_Flash.tga", 256, 64 },
    { "[Bar Fills] Onyxia_Horizontal_Spark", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\Onyxia_Horizontal_Spark.tga", 8, 64 },
    { "[Bar Fills] PandarenTraining_Circular_Flash", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\PandarenTraining_Circular_Flash.tga", 128, 128 },
    { "[Bar Fills] PandarenTrainingLarge_Circular_Flash", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\PandarenTrainingLarge_Circular_Flash.tga", 256, 256 },
    { "[Bar Fills] Pride_Horizontal_Bgnd", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\Pride_Horizontal_Bgnd.tga", 256, 64 },
    { "[Bar Fills] Pride_Horizontal_Fill", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\Pride_Horizontal_Fill.tga", 256, 64 },
    { "[Bar Fills] Pride_Horizontal_Spark", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\Pride_Horizontal_Spark.tga", 8, 64 },
    { "[Bar Fills] RevendrethAnima_Horizontal_Fill", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\RevendrethAnima_Horizontal_Fill.tga", 256, 64 },
    { "[Bar Fills] RevendrethAnima_Horizontal_Flash", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\RevendrethAnima_Horizontal_Flash.tga", 256, 64 },
    { "[Bar Fills] RevendrethAnima_Horizontal_Spark", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\RevendrethAnima_Horizontal_Spark.tga", 16, 64 },
    { "[Bar Fills] Rhyolith_Horizontal_Bgnd", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\Rhyolith_Horizontal_Bgnd.tga", 256, 64 },
    { "[Bar Fills] Rhyolith_Horizontal_Fill", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\Rhyolith_Horizontal_Fill.tga", 256, 64 },
    { "[Bar Fills] Rock_Circular_Frame", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\Rock_Circular_Frame.tga", 128, 128 },
    { "[Bar Fills] ShadowPaladinBar_Horizontal_Bgnd", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\ShadowPaladinBar_Horizontal_Bgnd.tga", 256, 64 },
    { "[Bar Fills] ShadowPaladinBar_Horizontal_Fill", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\ShadowPaladinBar_Horizontal_Fill.tga", 256, 64 },
    { "[Bar Fills] ShaWater_Horizontal_Spark", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\ShaWater_Horizontal_Spark.tga", 8, 64 },
    { "[Bar Fills] SivaraIce_Horizontal_Bgnd", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\SivaraIce_Horizontal_Bgnd.tga", 256, 64 },
    { "[Bar Fills] SivaraIce_Horizontal_Fill", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\SivaraIce_Horizontal_Fill.tga", 256, 64 },
    { "[Bar Fills] SivaraIce_Horizontal_Spark", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\SivaraIce_Horizontal_Spark.tga", 8, 64 },
    { "[Bar Fills] SivaraVenom_Horizontal_Bgnd", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\SivaraVenom_Horizontal_Bgnd.tga", 256, 64 },
    { "[Bar Fills] SivaraVenom_Horizontal_Fill", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\SivaraVenom_Horizontal_Fill.tga", 256, 64 },
    { "[Bar Fills] SivaraVenom_Horizontal_Flash", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\SivaraVenom_Horizontal_Flash.tga", 256, 64 },
    { "[Bar Fills] SivaraVenom_Horizontal_Spark", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\SivaraVenom_Horizontal_Spark.tga", 8, 64 },
    { "[Bar Fills] SpellPush-Frame-Smash", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\SpellPush-Frame-Smash.tga", 256, 128 },
    { "[Bar Fills] StoneGuardAmethyst_Horizontal_Fill", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\StoneGuardAmethyst_Horizontal_Fill.tga", 256, 64 },
    { "[Bar Fills] StoneGuardCobalt_Horizontal_Fill", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\StoneGuardCobalt_Horizontal_Fill.tga", 256, 64 },
    { "[Bar Fills] StoneGuardJade_Horizontal_Fill", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\StoneGuardJade_Horizontal_Fill.tga", 256, 64 },
    { "[Bar Fills] StoneGuardJasper_Horizontal_Fill", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\StoneGuardJasper_Horizontal_Fill.tga", 256, 64 },
    { "[Bar Fills] Thunderking_Horizontal_Bgnd", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\Thunderking_Horizontal_Bgnd.tga", 256, 64 },
    { "[Bar Fills] Thunderking_Horizontal_Fill", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\Thunderking_Horizontal_Fill.tga", 256, 64 },
    { "[Bar Fills] TwinOgronDistance_Horizontal_Spark", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\TwinOgronDistance_Horizontal_Spark.tga", 16, 64 },
    { "[Bar Fills] Water_Circular_Frame", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\Water_Circular_Frame.tga", 128, 128 },
    { "[Bar Fills] Xavius_Horizontal_Bgnd", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\Xavius_Horizontal_Bgnd.tga", 256, 64 },
    { "[Bar Fills] Xavius_Horizontal_Fill", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\Xavius_Horizontal_Fill.tga", 256, 64 },
    { "[Bar Fills] Xavius_Horizontal_Flash", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\Xavius_Horizontal_Flash.tga", 256, 64 },
    { "[Bar Fills] Xavius_Horizontal_Spark", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Bar_Fills\\Xavius_Horizontal_Spark.tga", 16, 64 },
    { "[DH Icons] artifactbook-demonhunter-cover", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\DH_Icons\\artifactbook-demonhunter-cover.tga", 256, 256 },
    { "[DH Icons] artifactbook-demonhunter-thealdrachiwarblades", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\DH_Icons\\artifactbook-demonhunter-thealdrachiwarblades.tga", 512, 256 },
    { "[DH Icons] artifactbook-demonhunter-twinbladesofthedeceiver", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\DH_Icons\\artifactbook-demonhunter-twinbladesofthedeceiver.tga", 512, 256 },
    { "[Flasks] Flask_Vertical_Fill", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Flasks\\Flask_Vertical_Fill.tga", 64, 128 },
    { "[Flasks] Flask_Vertical_Flash", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Flasks\\Flask_Vertical_Flash.tga", 64, 128 },
    { "[Flasks] Flask_Vertical_Frame", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Flasks\\Flask_Vertical_Frame.tga", 64, 128 },
    { "[Glyphs] Spell-Shadow-Acceptable", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Glyphs\\Spell-Shadow-Acceptable.tga", 1024, 1024 },
    { "[Glyphs] Thunderking_Pill_Bgnd", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Glyphs\\Thunderking_Pill_Bgnd.tga", 32, 64 },
    { "[Glyphs] Thunderking_Pill_Fill", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Glyphs\\Thunderking_Pill_Fill.tga", 32, 64 },
    { "[Glyphs] Thunderking_Pill_Flash", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Glyphs\\Thunderking_Pill_Flash.tga", 32, 64 },
    { "[Glyphs] UI-Glyph-Rune-1", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Glyphs\\UI-Glyph-Rune-1.tga", 64, 64 },
    { "[Glyphs] UI-Glyph-Rune-10", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Glyphs\\UI-Glyph-Rune-10.tga", 64, 64 },
    { "[Glyphs] UI-Glyph-Rune-12", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Glyphs\\UI-Glyph-Rune-12.tga", 64, 64 },
    { "[Glyphs] UI-Glyph-Rune-13", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Glyphs\\UI-Glyph-Rune-13.tga", 64, 64 },
    { "[Glyphs] UI-Glyph-Rune-14", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Glyphs\\UI-Glyph-Rune-14.tga", 64, 64 },
    { "[Glyphs] UI-Glyph-Rune-15", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Glyphs\\UI-Glyph-Rune-15.tga", 64, 64 },
    { "[Glyphs] UI-Glyph-Rune-16", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Glyphs\\UI-Glyph-Rune-16.tga", 64, 64 },
    { "[Glyphs] UI-Glyph-Rune-17", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Glyphs\\UI-Glyph-Rune-17.tga", 64, 64 },
    { "[Glyphs] UI-Glyph-Rune-18", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Glyphs\\UI-Glyph-Rune-18.tga", 64, 64 },
    { "[Glyphs] UI-Glyph-Rune-19", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Glyphs\\UI-Glyph-Rune-19.tga", 64, 64 },
    { "[Glyphs] UI-Glyph-Rune-2", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Glyphs\\UI-Glyph-Rune-2.tga", 64, 64 },
    { "[Glyphs] UI-Glyph-Rune-20", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Glyphs\\UI-Glyph-Rune-20.tga", 64, 64 },
    { "[Glyphs] UI-Glyph-Rune-3", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Glyphs\\UI-Glyph-Rune-3.tga", 64, 64 },
    { "[Glyphs] UI-Glyph-Rune-4", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Glyphs\\UI-Glyph-Rune-4.tga", 64, 64 },
    { "[Glyphs] UI-Glyph-Rune-5", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Glyphs\\UI-Glyph-Rune-5.tga", 64, 64 },
    { "[Glyphs] UI-Glyph-Rune-6", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Glyphs\\UI-Glyph-Rune-6.tga", 64, 64 },
    { "[Glyphs] UI-Glyph-Rune-7", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Glyphs\\UI-Glyph-Rune-7.tga", 64, 64 },
    { "[Glyphs] UI-Glyph-Rune-8", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Glyphs\\UI-Glyph-Rune-8.tga", 64, 64 },
    { "[Glyphs] UI-Glyph-Rune-9", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Glyphs\\UI-Glyph-Rune-9.tga", 64, 64 },
    { "[Glyphs] UI-Glyph-Rune1", "Interface\\AddOns\\XayaUI\\Media\\Graphics\\Glyphs\\UI-Glyph-Rune1.tga", 64, 64 },
}
